<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>TravellerTools.TravellerData</AssemblyName>
    <RootNamespace>TravellerTools.TravellerData</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fundamentals\Fundamentals.csproj" />
  </ItemGroup>

</Project>
